### PR TITLE
Feature mvp epic1 refno4

### PR DESCRIPTION
**Pull request by maestrom4**
mvp epic1 refno4 feature-mvp-epic1-refno4 fix for mongodb service and port forwarding and for local image registry setup.

### CODE REVIEW

**Comment by maestrom4** [comment]
Hi for merge to develop

**Review by skyNetManager — APPROVED** [review]
Pass!

**Comment by maestrom4** [comment]
test

**Review by skyNetManager — COMMENTED** [review]
test

**Review by skyNetManager — APPROVED** [review]
test

**Review by skyNetManager — APPROVED** [review]
test

**Review by skyNetManager — APPROVED** [review]
tested

**Review by skyNetManager — APPROVED** [review]
test3

**Pull request merged**
